version: '3'
services:
  db:
    container_name: postgres
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 112263
      POSTGRES_DB: catalog
  app:
    container_name: server
    build: ./server
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: catalog
      DB_PASSWORD: 112263
    depends_on: 
      - db
  client:
    container_name: client
    build: ./client
    expose:
      - 3000
    ports:
      - 3000:8080
    depends_on:
      - app